// 💬 A teammate's conversation as chat bubbles, for the companion app (/app): read from the Claude Code
// transcript its hooks named (see workers.ts, usage.ts), not from the terminal. The human's prompts
// become 'user' messages, cleaned of what the office wraps them in; each turn's replies become one
// 'assistant' message, with the tools it used listed in a few words.
//
// The transcript format is Claude Code's own and may change: a line this doesn't understand is
// skipped, never fatal. Only the one file named is read (no subagent transcripts).

import { statSync } from 'node:fs';
import type { ChatAttachment, ChatMessage, ChatResponse, ChatTool, TeamEntry, TeamResponse } from '../shared/app-api.js';
import type { WorkerInfo } from '../shared/protocol.js';
import { TEAM_BY_ID } from '../shared/team.js';
import { readNewLines } from './usage.js';

export const CHAT_MAX_MESSAGES = 300;
export const CHAT_MAX_TEXT = 40_000;
/** Tools listed on one reply: a very long turn keeps the first ones. */
const MAX_TOOLS = 500;
const SUMMARY_MAX = 60;
/** Transcripts whose parse is kept, for the app polling every few seconds. */
const CACHE_FILES = 64;

// ---------------------------------------------------------------------------------------------
// Cleaning up a prompt

/** What ends the brief a roster teammate or a board agent gets before its first task (see teamBrief(), stationBrief()). */
const BRIEF_END = /\n\n(?:Your first task:|The request:)\n\n/;
/** A brief with no task after it: the teammate just says hello (see teamBrief()). */
const BRIEF_ONLY = /then wait for your first task\.$/;

/**
 * The first prompt of a session without the brief in front of it: the real task, or null when the
 * prompt was nothing but the brief. Briefs all open with "You're …"; anything else is left alone.
 */
export function stripBrief(text: string): string | null {
  if (!text.startsWith("You're ")) return text;
  const m = BRIEF_END.exec(text);
  if (m) return text.slice(m.index + m[0].length).trim();
  return BRIEF_ONLY.test(text.trim()) ? null : text;
}

const ATTACH_TYPES: Record<string, ChatAttachment['kind']> = { png: 'image', jpg: 'image', jpeg: 'image', webp: 'image', gif: 'image', pdf: 'pdf' };
/** The line attachNote() (client/attach.ts) puts above the list of paths. */
const NOTE_LINE = /^📎 .* attached /u;
/** What the terminal types in for a file dropped on it (client/ui/terminal.ts). */
const INLINE_NOTE = /\(file to read, then note what it shows in memory\/: ([^\n]+?\.(?:png|jpe?g|webp|gif|pdf))\) ?/giu;

function attachmentOf(p: string): ChatAttachment {
  const name = p.split(/[\\/]/).pop() || p;
  const ext = /\.([a-z0-9]+)$/i.exec(name)?.[1].toLowerCase() ?? '';
  return { path: p, name, kind: ATTACH_TYPES[ext] ?? 'image' };
}

/** Takes the office's notes about attached files out of a prompt, and hands back the files they name. */
export function extractAttachments(text: string): { text: string; attachments: ChatAttachment[] } {
  const found: string[] = [];
  const lines = text.split('\n');
  for (let i = 0; i < lines.length; i++) {
    if (!NOTE_LINE.test(lines[i])) continue;
    let j = i + 1;
    while (j < lines.length && lines[j].startsWith('- ')) found.push(lines[j++].slice(2).trim());
    // A 📎 line with no list under it is the human's own words.
    if (j === i + 1) continue;
    lines.splice(i, j - i);
    i--;
  }
  const out = lines.join('\n').replace(INLINE_NOTE, (_all, p: string) => {
    found.push(p.trim());
    return '';
  });
  return { text: out.trim(), attachments: found.filter(Boolean).map(attachmentOf) };
}

/** Context Claude Code or its hooks wrap into a prompt, which the human never typed. */
const WRAPPED = /<(system-reminder|user-prompt-submit-hook)>[\s\S]*?<\/\1>/g;
/** Prompts that aren't the human talking: slash commands and their output, ! commands, hook output, interruptions. */
const NOT_SAID =
  /^(?:<command-(?:name|message|args)>|<task-notification>|<local-command-|<bash-(?:input|stdout|stderr)>|This floor's shared memory right now \(|\[Request interrupted by user|Caveat: The messages below were generated by the user)/;

/** A user record's words as the human meant them, or null when it wasn't the human talking. */
export function cleanPrompt(raw: string): string | null {
  const text = raw.replace(/\r\n?/g, '\n').replace(WRAPPED, '').trim();
  if (!text || NOT_SAID.test(text)) return null;
  return text;
}

// ---------------------------------------------------------------------------------------------
// Tool summaries

const oneLine = (s: string) => s.replace(/\s+/g, ' ').trim();
const clip = (s: string, n = SUMMARY_MAX) => (s.length > n ? `${s.slice(0, n - 1)}…` : s);
const baseName = (p: string) => p.split(/[\\/]/).filter(Boolean).pop() ?? p;
const strIn = (input: any, key: string) => (typeof input?.[key] === 'string' ? (input[key] as string) : '');

/** What a tool call did, in a few words: the file it read or edited, the command it ran, what it searched for. */
export function toolSummary(name: string, input: unknown): string {
  const i = input as any;
  switch (name) {
    case 'Read':
    case 'Write':
    case 'Edit':
    case 'MultiEdit':
      return clip(baseName(strIn(i, 'file_path')));
    case 'NotebookEdit':
      return clip(baseName(strIn(i, 'notebook_path')));
    case 'Bash':
    case 'PowerShell':
      return clip(oneLine(strIn(i, 'command')));
    case 'Grep':
    case 'Glob':
      return clip(oneLine(strIn(i, 'pattern')));
    case 'WebFetch': {
      const url = strIn(i, 'url');
      try {
        return clip(new URL(url).host);
      } catch {
        return clip(url);
      }
    }
    case 'WebSearch':
    case 'ToolSearch':
      return clip(oneLine(strIn(i, 'query')));
    case 'Agent':
    case 'Task':
      return clip(oneLine(strIn(i, 'description')));
    case 'Skill':
      return clip(strIn(i, 'skill'));
    case 'TodoWrite':
      return Array.isArray(i?.todos) ? `${i.todos.length} to-dos` : '';
  }
  // Anything else: its first short string argument says enough.
  if (i && typeof i === 'object') {
    for (const v of Object.values(i)) if (typeof v === 'string' && v.trim()) return clip(oneLine(v));
  }
  return '';
}

// ---------------------------------------------------------------------------------------------
// Reading a transcript

interface Parse {
  size: number;
  mtimeMs: number;
  /** Bytes read so far, always at a line boundary (see readNewLines). */
  cursor: { offset: number };
  messages: ChatMessage[];
  /** The reply of the turn in progress, still being added to. */
  open?: ChatMessage & { tools: ChatTool[] };
  /** What the open reply has said and done already, by block. */
  seen: Set<string>;
  /** A human prompt was seen already: briefs only come first. */
  prompted: boolean;
  lines: number;
  lastAt: number;
}

const cache = new Map<string, Parse>();

const newParse = (): Parse => ({ size: -1, mtimeMs: -1, cursor: { offset: 0 }, messages: [], seen: new Set(), prompted: false, lines: 0, lastAt: 0 });

function timeOf(p: Parse, line: any): number {
  const at = typeof line.timestamp === 'string' ? Date.parse(line.timestamp) : NaN;
  if (Number.isFinite(at)) p.lastAt = at;
  return p.lastAt;
}

const idOf = (p: Parse, line: any, kind: string) => (typeof line.uuid === 'string' && line.uuid ? line.uuid : `${kind}-${p.lines}`);

function addUser(p: Parse, line: any) {
  // Claude Code's own records: context it added, a compaction summary, a subagent's conversation.
  if (line.isMeta || line.isCompactSummary || line.isVisibleInTranscriptOnly || line.isSidechain) return;
  // Newer versions say where a prompt came from: only a human's counts (not a finished background
  // task's report). What the agent says back to one is a reply of its own, though.
  if (typeof line.origin?.kind === 'string' && line.origin.kind !== 'human') {
    p.open = undefined;
    return;
  }
  // A tool's result belongs to the reply in progress.
  if (line.toolUseResult !== undefined) return;
  const content = line.message?.content;
  let raw: string;
  if (typeof content === 'string') raw = content;
  else if (Array.isArray(content)) {
    if (content.some((b) => b?.type === 'tool_result')) return;
    raw = content
      .filter((b) => b?.type === 'text' && typeof b.text === 'string')
      .map((b) => b.text as string)
      .join('\n\n');
    // A picture pasted straight into the terminal travels inside the prompt, with no file to show.
    if (!raw.trim() && content.some((b) => b?.type === 'image')) raw = '(a pasted picture)';
  } else return;
  let text = cleanPrompt(raw);
  if (text === null) return;
  const first = !p.prompted;
  p.prompted = true;
  p.open = undefined;
  if (first) {
    text = stripBrief(text);
    if (text === null) return;
  }
  const { text: said, attachments } = extractAttachments(text);
  if (!said && !attachments.length) return;
  const msg: ChatMessage = { id: idOf(p, line, 'user'), role: 'user', text: capText(said), at: timeOf(p, line) };
  if (attachments.length) msg.attachments = attachments;
  p.messages.push(msg);
}

function addAssistant(p: Parse, line: any) {
  if (line.isSidechain) return;
  const msg = line.message;
  if (!msg || typeof msg !== 'object' || !Array.isArray(msg.content)) return;
  const at = timeOf(p, line);
  const mid = typeof msg.id === 'string' ? msg.id : '';
  for (const b of msg.content) {
    if (!b || typeof b !== 'object') continue;
    if (b.type === 'text' && typeof b.text === 'string' && b.text.trim()) {
      const open = openReply(p, line, at);
      // The same message can be logged again with the blocks so far: don't say it twice.
      const key = `t:${mid}:${b.text}`;
      if (p.seen.has(key)) continue;
      p.seen.add(key);
      if (open.text.length <= CHAT_MAX_TEXT) open.text = open.text ? `${open.text}\n\n${b.text.trim()}` : b.text.trim();
    } else if (b.type === 'tool_use' && typeof b.name === 'string') {
      const open = openReply(p, line, at);
      const key = `u:${typeof b.id === 'string' ? b.id : `${mid}:${open.tools.length}`}`;
      if (p.seen.has(key)) continue;
      p.seen.add(key);
      if (open.tools.length < MAX_TOOLS) open.tools.push({ name: b.name, summary: toolSummary(b.name, b.input) });
    }
  }
}

/** The reply this turn's words go into, started on its first words. */
function openReply(p: Parse, line: any, at: number) {
  if (!p.open) {
    p.open = { id: idOf(p, line, 'assistant'), role: 'assistant', text: '', at, tools: [] };
    p.seen = new Set();
    p.messages.push(p.open);
  }
  p.open.at = at;
  return p.open;
}

function apply(p: Parse, raw: string) {
  p.lines++;
  let line: any;
  try {
    line = JSON.parse(raw);
  } catch {
    return;
  }
  if (!line || typeof line !== 'object') return;
  if (line.type === 'user') addUser(p, line);
  else if (line.type === 'assistant') addAssistant(p, line);
  // Everything else (attachments, hook output, system notes, cost tallies) isn't said by anyone.
}

const capText = (s: string) => (s.length > CHAT_MAX_TEXT ? `${s.slice(0, CHAT_MAX_TEXT - 1)}…` : s);

/** A copy for the response: the parse keeps adding to its own messages. */
function view(m: ChatMessage): ChatMessage {
  const out: ChatMessage = { id: m.id, role: m.role, text: capText(m.text), at: m.at };
  if (m.attachments?.length) out.attachments = m.attachments.map((a) => ({ ...a }));
  if (m.tools?.length) out.tools = m.tools.map((t) => ({ ...t }));
  return out;
}

/**
 * The conversation in a transcript, oldest first, the newest CHAT_MAX_MESSAGES. Cached by the file's
 * size and modified time, and only what was appended since is read, so it can be asked every second.
 */
export function readChat(file: string | undefined): ChatMessage[] {
  if (!file) return [];
  let st: import('node:fs').Stats;
  try {
    st = statSync(file);
  } catch {
    cache.delete(file);
    return [];
  }
  if (!st.isFile()) return [];
  let p = cache.get(file);
  // Shorter than what was read: not the file we knew (see readNewLines). Start over.
  if (!p || st.size < p.cursor.offset) p = newParse();
  cache.delete(file);
  cache.set(file, p);
  for (const k of cache.keys()) {
    if (cache.size <= CACHE_FILES) break;
    cache.delete(k);
  }
  if (st.size !== p.size || st.mtimeMs !== p.mtimeMs) {
    p.size = st.size;
    p.mtimeMs = st.mtimeMs;
    for (const line of readNewLines(file, p.cursor)) apply(p, line);
    // Keep the parse bounded; the reply in progress is always among the newest.
    if (p.messages.length > CHAT_MAX_MESSAGES * 2) p.messages.splice(0, p.messages.length - CHAT_MAX_MESSAGES);
  }
  return p.messages.slice(-CHAT_MAX_MESSAGES).map(view);
}

// ---------------------------------------------------------------------------------------------
// Who's who

/** When a transcript last changed (ms), or undefined when there isn't one yet. */
function modifiedAt(file: string | undefined): number | undefined {
  if (!file) return undefined;
  try {
    return statSync(file).mtimeMs;
  } catch {
    return undefined;
  }
}

/** A worker as the app lists it (see TeamEntry). */
export function teamEntry(info: WorkerInfo, transcript: string | undefined): TeamEntry {
  const e: TeamEntry = { id: info.id, name: info.name, color: info.color, status: info.status, acked: info.acked, kind: info.kind };
  const member = info.role ? TEAM_BY_ID.get(info.role) : undefined;
  if (info.role) e.role = info.role;
  if (member) e.emoji = member.emoji;
  if (info.waitingSince !== undefined) e.waitingSince = info.waitingSince;
  if (info.activity) e.activity = info.activity;
  if (info.title) e.title = info.title;
  if (info.parked) e.parked = true;
  if (info.meeting) e.meeting = info.meeting;
  const at = modifiedAt(transcript);
  if (at !== undefined) e.lastMessageAt = at;
  return e;
}

/** What /api/team needs of a floor: its name and its workers. */
export interface TeamFloor {
  id: string;
  def: { name: string };
  workers: { list(): WorkerInfo[]; transcriptOf(id: string): string | undefined };
}

/** GET /api/team: every floor's workers. Empty kiosk seats have no worker, so they never show. */
export function teamOf(floors: Iterable<TeamFloor>): TeamResponse {
  return {
    floors: [...floors].map((f) => ({ id: f.id, name: f.def.name, workers: f.workers.list().map((w) => teamEntry(w, f.workers.transcriptOf(w.id))) })),
  };
}

/** GET /api/chat: who the worker is and what's been said. */
export function workerChat(info: WorkerInfo, transcript: string | undefined): ChatResponse {
  return { worker: teamEntry(info, transcript), messages: readChat(transcript) };
}

/** Forgets every cached parse (tests). */
export function clearChatCache() {
  cache.clear();
}
